repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: migrations/|settings/
# -   repo: local
#     hooks:
#     - id: test
#       name: test
#       entry: python manage.py test
#       always_run: true
#       pass_filenames: false
#       language: system